---
Sections:
  VERSION 10:
    order: 1
    entries:
    - name : Version Begins
      file : VersionBegin.md
      order : 10
  Overview:
    order: 10
    entries:
    - name : Show me the code!
      file : ShowMeTheCode.md
      order : 10
  Brighter Configuration:
    order: 20
    entries:
    - name : Basic Configuration
      file : BrighterBasicConfiguration.md
      order : 10      
  END OF VERSION:
    order: 999
    entries:   
    - name : Version Ends
      file : VersionEnd.md
      order : 20
...